## BLINDING FOR THE RESUME
#blind: "blind" 
#blinda: "span"

## DEACTIVATE BLINDING
blind: ""
blinda: "a"


###################################
###################################


title: William Michael Landau
baseurl: ""
url: "https://wlandau.github.io"
github: "https://github.com/wlandau.github.io"

kramdown:
  input: GFM
permalink: pretty

disqus_shortname: wlandau
google_analytics:

gems:
  - jekyll-feed